type ChampionData = {
  id: string;
  key: string;
  name: string;
};
type ChampionJson = {
  type: string;
  format: string;
  version: string;
  data: { [key: number]: ChampionData };
};

const champions: ChampionJson = {
  type: 'champion',
  format: 'standAloneComplex',
  version: '15.23.1',
  data: {
    1: { id: 'Annie', key: '1', name: 'Annie' },
    2: { id: 'Olaf', key: '2', name: 'Olaf' },
    3: { id: 'Galio', key: '3', name: 'Galio' },
    4: { id: 'TwistedFate', key: '4', name: 'Twisted Fate' },
    5: { id: 'XinZhao', key: '5', name: 'Xin Zhao' },
    6: { id: 'Urgot', key: '6', name: 'Urgot' },
    7: { id: 'Leblanc', key: '7', name: 'LeBlanc' },
    8: { id: 'Vladimir', key: '8', name: 'Vladimir' },
    9: { id: 'Fiddlesticks', key: '9', name: 'Fiddlesticks' },
    10: { id: 'Kayle', key: '10', name: 'Kayle' },
    11: { id: 'MasterYi', key: '11', name: 'Master Yi' },
    12: { id: 'Alistar', key: '12', name: 'Alistar' },
    13: { id: 'Ryze', key: '13', name: 'Ryze' },
    14: { id: 'Sion', key: '14', name: 'Sion' },
    15: { id: 'Sivir', key: '15', name: 'Sivir' },
    16: { id: 'Soraka', key: '16', name: 'Soraka' },
    17: { id: 'Teemo', key: '17', name: 'Teemo' },
    18: { id: 'Tristana', key: '18', name: 'Tristana' },
    19: { id: 'Warwick', key: '19', name: 'Warwick' },
    20: { id: 'Nunu', key: '20', name: 'Nunu & Willump' },
    21: { id: 'MissFortune', key: '21', name: 'Miss Fortune' },
    22: { id: 'Ashe', key: '22', name: 'Ashe' },
    23: { id: 'Tryndamere', key: '23', name: 'Tryndamere' },
    24: { id: 'Jax', key: '24', name: 'Jax' },
    25: { id: 'Morgana', key: '25', name: 'Morgana' },
    26: { id: 'Zilean', key: '26', name: 'Zilean' },
    27: { id: 'Singed', key: '27', name: 'Singed' },
    28: { id: 'Evelynn', key: '28', name: 'Evelynn' },
    29: { id: 'Twitch', key: '29', name: 'Twitch' },
    30: { id: 'Karthus', key: '30', name: 'Karthus' },
    31: { id: 'Chogath', key: '31', name: "Cho'Gath" },
    32: { id: 'Amumu', key: '32', name: 'Amumu' },
    33: { id: 'Rammus', key: '33', name: 'Rammus' },
    34: { id: 'Anivia', key: '34', name: 'Anivia' },
    35: { id: 'Shaco', key: '35', name: 'Shaco' },
    36: { id: 'DrMundo', key: '36', name: 'Dr. Mundo' },
    37: { id: 'Sona', key: '37', name: 'Sona' },
    38: { id: 'Kassadin', key: '38', name: 'Kassadin' },
    39: { id: 'Irelia', key: '39', name: 'Irelia' },
    40: { id: 'Janna', key: '40', name: 'Janna' },
    41: { id: 'Gangplank', key: '41', name: 'Gangplank' },
    42: { id: 'Corki', key: '42', name: 'Corki' },
    43: { id: 'Karma', key: '43', name: 'Karma' },
    44: { id: 'Taric', key: '44', name: 'Taric' },
    45: { id: 'Veigar', key: '45', name: 'Veigar' },
    48: { id: 'Trundle', key: '48', name: 'Trundle' },
    50: { id: 'Swain', key: '50', name: 'Swain' },
    51: { id: 'Caitlyn', key: '51', name: 'Caitlyn' },
    53: { id: 'Blitzcrank', key: '53', name: 'Blitzcrank' },
    54: { id: 'Malphite', key: '54', name: 'Malphite' },
    55: { id: 'Katarina', key: '55', name: 'Katarina' },
    56: { id: 'Nocturne', key: '56', name: 'Nocturne' },
    57: { id: 'Maokai', key: '57', name: 'Maokai' },
    58: { id: 'Renekton', key: '58', name: 'Renekton' },
    59: { id: 'JarvanIV', key: '59', name: 'Jarvan IV' },
    60: { id: 'Elise', key: '60', name: 'Elise' },
    61: { id: 'Orianna', key: '61', name: 'Orianna' },
    62: { id: 'MonkeyKing', key: '62', name: 'Wukong' },
    63: { id: 'Brand', key: '63', name: 'Brand' },
    64: { id: 'LeeSin', key: '64', name: 'Lee Sin' },
    67: { id: 'Vayne', key: '67', name: 'Vayne' },
    68: { id: 'Rumble', key: '68', name: 'Rumble' },
    69: { id: 'Cassiopeia', key: '69', name: 'Cassiopeia' },
    72: { id: 'Skarner', key: '72', name: 'Skarner' },
    74: { id: 'Heimerdinger', key: '74', name: 'Heimerdinger' },
    75: { id: 'Nasus', key: '75', name: 'Nasus' },
    76: { id: 'Nidalee', key: '76', name: 'Nidalee' },
    77: { id: 'Udyr', key: '77', name: 'Udyr' },
    78: { id: 'Poppy', key: '78', name: 'Poppy' },
    79: { id: 'Gragas', key: '79', name: 'Gragas' },
    80: { id: 'Pantheon', key: '80', name: 'Pantheon' },
    81: { id: 'Ezreal', key: '81', name: 'Ezreal' },
    82: { id: 'Mordekaiser', key: '82', name: 'Mordekaiser' },
    83: { id: 'Yorick', key: '83', name: 'Yorick' },
    84: { id: 'Akali', key: '84', name: 'Akali' },
    85: { id: 'Kennen', key: '85', name: 'Kennen' },
    86: { id: 'Garen', key: '86', name: 'Garen' },
    89: { id: 'Leona', key: '89', name: 'Leona' },
    90: { id: 'Malzahar', key: '90', name: 'Malzahar' },
    91: { id: 'Talon', key: '91', name: 'Talon' },
    92: { id: 'Riven', key: '92', name: 'Riven' },
    96: { id: 'KogMaw', key: '96', name: "Kog'Maw" },
    98: { id: 'Shen', key: '98', name: 'Shen' },
    99: { id: 'Lux', key: '99', name: 'Lux' },
    101: { id: 'Xerath', key: '101', name: 'Xerath' },
    102: { id: 'Shyvana', key: '102', name: 'Shyvana' },
    103: { id: 'Ahri', key: '103', name: 'Ahri' },
    104: { id: 'Graves', key: '104', name: 'Graves' },
    105: { id: 'Fizz', key: '105', name: 'Fizz' },
    106: { id: 'Volibear', key: '106', name: 'Volibear' },
    107: { id: 'Rengar', key: '107', name: 'Rengar' },
    110: { id: 'Varus', key: '110', name: 'Varus' },
    111: { id: 'Nautilus', key: '111', name: 'Nautilus' },
    112: { id: 'Viktor', key: '112', name: 'Viktor' },
    113: { id: 'Sejuani', key: '113', name: 'Sejuani' },
    114: { id: 'Fiora', key: '114', name: 'Fiora' },
    115: { id: 'Ziggs', key: '115', name: 'Ziggs' },
    117: { id: 'Lulu', key: '117', name: 'Lulu' },
    119: { id: 'Draven', key: '119', name: 'Draven' },
    120: { id: 'Hecarim', key: '120', name: 'Hecarim' },
    121: { id: 'Khazix', key: '121', name: "Kha'Zix" },
    122: { id: 'Darius', key: '122', name: 'Darius' },
    126: { id: 'Jayce', key: '126', name: 'Jayce' },
    127: { id: 'Lissandra', key: '127', name: 'Lissandra' },
    131: { id: 'Diana', key: '131', name: 'Diana' },
    133: { id: 'Quinn', key: '133', name: 'Quinn' },
    134: { id: 'Syndra', key: '134', name: 'Syndra' },
    136: { id: 'AurelionSol', key: '136', name: 'Aurelion Sol' },
    141: { id: 'Kayn', key: '141', name: 'Kayn' },
    142: { id: 'Zoe', key: '142', name: 'Zoe' },
    143: { id: 'Zyra', key: '143', name: 'Zyra' },
    145: { id: 'Kaisa', key: '145', name: "Kai'Sa" },
    147: { id: 'Seraphine', key: '147', name: 'Seraphine' },
    150: { id: 'Gnar', key: '150', name: 'Gnar' },
    154: { id: 'Zac', key: '154', name: 'Zac' },
    157: { id: 'Yasuo', key: '157', name: 'Yasuo' },
    161: { id: 'Velkoz', key: '161', name: "Vel'Koz" },
    163: { id: 'Taliyah', key: '163', name: 'Taliyah' },
    164: { id: 'Camille', key: '164', name: 'Camille' },
    166: { id: 'Akshan', key: '166', name: 'Akshan' },
    200: { id: 'Belveth', key: '200', name: "Bel'Veth" },
    201: { id: 'Braum', key: '201', name: 'Braum' },
    202: { id: 'Jhin', key: '202', name: 'Jhin' },
    203: { id: 'Kindred', key: '203', name: 'Kindred' },
    221: { id: 'Zeri', key: '221', name: 'Zeri' },
    222: { id: 'Jinx', key: '222', name: 'Jinx' },
    223: { id: 'TahmKench', key: '223', name: 'Tahm Kench' },
    233: { id: 'Briar', key: '233', name: 'Briar' },
    234: { id: 'Viego', key: '234', name: 'Viego' },
    235: { id: 'Senna', key: '235', name: 'Senna' },
    236: { id: 'Lucian', key: '236', name: 'Lucian' },
    238: { id: 'Zed', key: '238', name: 'Zed' },
    240: { id: 'Kled', key: '240', name: 'Kled' },
    245: { id: 'Ekko', key: '245', name: 'Ekko' },
    246: { id: 'Qiyana', key: '246', name: 'Qiyana' },
    254: { id: 'Vi', key: '254', name: 'Vi' },
    266: { id: 'Aatrox', key: '266', name: 'Aatrox' },
    267: { id: 'Nami', key: '267', name: 'Nami' },
    268: { id: 'Azir', key: '268', name: 'Azir' },
    350: { id: 'Yuumi', key: '350', name: 'Yuumi' },
    360: { id: 'Samira', key: '360', name: 'Samira' },
    412: { id: 'Thresh', key: '412', name: 'Thresh' },
    420: { id: 'Illaoi', key: '420', name: 'Illaoi' },
    421: { id: 'RekSai', key: '421', name: "Rek'Sai" },
    427: { id: 'Ivern', key: '427', name: 'Ivern' },
    429: { id: 'Kalista', key: '429', name: 'Kalista' },
    432: { id: 'Bard', key: '432', name: 'Bard' },
    497: { id: 'Rakan', key: '497', name: 'Rakan' },
    498: { id: 'Xayah', key: '498', name: 'Xayah' },
    516: { id: 'Ornn', key: '516', name: 'Ornn' },
    517: { id: 'Sylas', key: '517', name: 'Sylas' },
    518: { id: 'Neeko', key: '518', name: 'Neeko' },
    523: { id: 'Aphelios', key: '523', name: 'Aphelios' },
    526: { id: 'Rell', key: '526', name: 'Rell' },
    555: { id: 'Pyke', key: '555', name: 'Pyke' },
    711: { id: 'Vex', key: '711', name: 'Vex' },
    777: { id: 'Yone', key: '777', name: 'Yone' },
    799: { id: 'Ambessa', key: '799', name: 'Ambessa' },
    800: { id: 'Mel', key: '800', name: 'Mel' },
    804: { id: 'Yunara', key: '804', name: 'Yunara' },
    875: { id: 'Sett', key: '875', name: 'Sett' },
    876: { id: 'Lillia', key: '876', name: 'Lillia' },
    887: { id: 'Gwen', key: '887', name: 'Gwen' },
    888: { id: 'Renata', key: '888', name: 'Renata Glasc' },
    893: { id: 'Aurora', key: '893', name: 'Aurora' },
    895: { id: 'Nilah', key: '895', name: 'Nilah' },
    897: { id: 'KSante', key: '897', name: "K'Sante" },
    901: { id: 'Smolder', key: '901', name: 'Smolder' },
    902: { id: 'Milio', key: '902', name: 'Milio' },
    904: { id: 'Zaahen', key: '904', name: 'Zaahen' },
    910: { id: 'Hwei', key: '910', name: 'Hwei' },
    950: { id: 'Naafiri', key: '950', name: 'Naafiri' },
  },
};
export default champions;
