/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as SummonerSummonerNameRouteImport } from './pages/summoner/$summonerName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummonerSummonerNameRoute = SummonerSummonerNameRouteImport.update({
  id: '/summoner/$summonerName',
  path: '/summoner/$summonerName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/summoner/$summonerName': typeof SummonerSummonerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/summoner/$summonerName': typeof SummonerSummonerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/summoner/$summonerName': typeof SummonerSummonerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/summoner/$summonerName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/summoner/$summonerName'
  id: '__root__' | '/' | '/summoner/$summonerName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SummonerSummonerNameRoute: typeof SummonerSummonerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summoner/$summonerName': {
      id: '/summoner/$summonerName'
      path: '/summoner/$summonerName'
      fullPath: '/summoner/$summonerName'
      preLoaderRoute: typeof SummonerSummonerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SummonerSummonerNameRoute: SummonerSummonerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
